all:
	g++ middle2r.c --std=c++11 -fopenmp -O3 -o middle2r
	g++ middle3r.c --std=c++11 -fopenmp -O3 -o middle3r
	g++ middle4r.c --std=c++11 -fopenmp -O3 -o middle4r
	g++ middle5r.c --std=c++11 -fopenmp -O3 -o middle5r
	g++ middle6r.c --std=c++11 -fopenmp -O3 -o middle6r
clean:
	rm -f *.o middle2r middle3r middle4r middle5r middle6r